# Generated by Django 5.2.4 on 2025-07-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mamamboga',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
