# Generated by Django 5.2.4 on 2025-07-20 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_mamamboga_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mamamboga',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mamamboga_image/'),
        ),
        migrations.AddField(
            model_name='mamamboga',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='role',
            field=models.CharField(choices=[('Trainer', 'trainer'), ('Supplier', 'supplier')], default='supplier', max_length=20),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mamamboga',
            name='pin',
            field=models.CharField(max_length=32),
        ),
    ]
